In [1]:
import numpy as np  # The swiss knife of the data scientist.

In [2]:
alist = [1, 2, 3, 4, 5]   # Define a python list. It looks like an np array
narray = np.array([1, 2, 3, 4]) # Define a numpy array

In [3]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# Matrix or array of arrays 


In [15]:
npmatrix1 = np.array([narray,narray,narray]) # matrix initialized with numpy arrays
npmatrix2 = np.array ([alist,alist,alist]) # matrix initialized with lists
npmatrix3 = np.array([narray,[1,1,1,1],narray]) # matrix initilaized with both types

print(npmatrix1)
print(type(npmatrix1),type(npmatrix1[0]))
print(npmatrix2)
print(type(npmatrix2),type(npmatrix2[0]))
print(npmatrix3)
print(type(npmatrix3),type(npmatrix3[0]))


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [17]:
okmatrix = np.array([[1,2],[3,4]])
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [19]:
#example 2 
badmatrix = np.array([[1,2],[3,4],[7,8,9,0]])
print(badmatrix)
print(badmatrix*3)

[list([1, 2]) list([3, 4]) list([7, 8, 9, 0])]
[list([1, 2, 1, 2, 1, 2]) list([3, 4, 3, 4, 3, 4])
 list([7, 8, 9, 0, 7, 8, 9, 0, 7, 8, 9, 0])]


# scaling and translation

In [22]:
# scale by 2 and translate 1 unit
result = okmatrix*2+1
print(result)

[[3 5]
 [7 9]]


In [23]:
# Add two sum compatible matrices
result1 = okmatrix + okmatrix
print(result1)

# Subtract two sum compatible matrices. This is called the difference vector
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [24]:
result = okmatrix * okmatrix # Multiply each element by itself
print(result)

[[ 1  4]
 [ 9 16]]


In [25]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) # Define a 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [26]:
# transpose doesnt affect 1 D array
nparray = np.array([1, 2, 3, 4]) # Define an array
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


In [27]:
nparray = np.array([[1, 2, 3, 4]]) # Define a 1 x 4 matrix. Note the 2 level of square brackets
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


## Get the norm of a nparray or matrix

In linear algebra, the norm of an n-dimensional vector $\vec a$   is defined as:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

Calculating the norm of vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linalg**, including the **norm** function. Let us see how to get the norm a given array or matrix:

In [30]:
nparray1 = np.array([1,2,3,4])
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1,2],[3,4]])
norm2 = np.linalg.norm(nparray2)

print(norm1)
print(norm2)

# without any parameters the norm function trets the matri as just being an array of numbers

5.477225575051661
5.477225575051661


In [31]:
nparray3 = np.array([[1,1],[2,2],[3,3]])

normbycol = np.linalg.norm(nparray3,axis =0) # returns 2 elements (for each cols)
normbyrow = np.linalg.norm(nparray3,axis =1) # returns 3 elements (for each row)

print(normbycol)
print(normbyrow)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [33]:
nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array

flavor1 = np.dot(nparray1, nparray2) # Recommended way
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2) # Ok way
print(flavor2)

flavor3 = nparray1 @ nparray2         # Geeks way
print(flavor3)

# As you never should do:             # Noobs way
flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b
    
print(flavor4)

38
38
38
38


In [34]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4])) # Dot product on nparrays
norm2 = np.dot([1, 2], [3, 4]) # Dot product on python lists

print(norm1, '=', norm2 )

11 = 11


In [35]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. 

sumByCols = np.sum(nparray2, axis=0) # Get the sum for each column. Returns 2 elements
sumByRows = np.sum(nparray2, axis=1) # get the sum for each row. Returns 3 elements

print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


In [36]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. Chosen to be a matrix with 0 mean

mean = np.mean(nparray2) # Get the mean for the whole matrix
meanByCols = np.mean(nparray2, axis=0) # Get the mean for each column. Returns 2 elements
meanByRows = np.mean(nparray2, axis=1) # get the mean for each row. Returns 3 elements

print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)


Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [39]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2 - np.mean(nparray2, axis=0) # Remove the mean for each column

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


In [40]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

mean1 = np.mean(nparray2) # Static way
mean2 = nparray2.mean()   # Dinamic way

print(mean1, ' == ', mean2)

3.0  ==  3.0


In [41]:
# use static way always !!